### PR TITLE
Feature/dhsc 71 banner support

### PR DESCRIPTION
**Pull request by matt-lambert-TPX**
- Adds banner component to Homepage CT with optional title, text and link fields
- Subject to design changes. The component currently uses LocalGov banner styles. 

Screenshot 2023-02-27 at 16 15 24

### CODE REVIEW

**Comment by endre-soo-TPX** [comment]
Looking great, @matt-lambert-TPX , bit 
- do we have to make the Banner required? I think optional would provide more flexibility for editors
- can you set `develop` as the target branch 
- can you run `make coding-standards` and resolve any issues, please? 

Thanks!

**Comment by matt-lambert-TPX** [comment]
> * make coding-standards

Hey @endre-soo-TPX, thanks for reviewing.

- do we have to make the Banner required? I think optional would provide more flexibility for editors
   _Good point, banner is now optional_
- can you set develop as the target branch
_develop not set as target branch_
- can you run make coding-standards and resolve any issues, please?
_Coding standards now fixed_

**Comment by endre-soo-TPX** [comment]
Hey @matt-lambert-TPX ,

Looking great 🙌 

Just one small thing left, can you add back `purge_queuer_coretags` to the config like:

```
diff --git a/config/default/sync/core.extension.yml b/config/default/sync/core.extension.yml
index 70be531..9eb7cb4 100644
--- a/config/default/sync/core.extension.yml
+++ b/config/default/sync/core.extension.yml
@@ -77,6 +77,7 @@ module:
   purge: 0
   purge_drush: 0
   purge_processor_cron: 0
+  purge_queuer_coretags: 0
   purge_ui: 0
   quickedit: 0
   responsive_image: 0
```


At some point this got removed and is causing issues aver since. 

After this you don't have to wait for review, just merge into `develop`.


Thanks!

**Comment by matt-lambert-TPX** [comment]
Hey @endre-soo-TPX, thanks for reviewing, config now updated with above entry. Cheers!

**Pull request merged**
